language: python
python:
  - "3.0"
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
script:
  - cd examples
  - jupyter nbconvert --execute inv_example.ipynb
