language: python
python:
#  - "3.3"
#  - "3.4"
#  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
  - apt-install jupyter
script:
  - jupyter nbconvert --execute examples/inv_example.ipynb
