language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python setup.py -q install
script:
  - cd examples
  - jupyter nbconvert --execute inv_example.ipynb
